### ISSUE TITLE
Multiple Resolution Capabilities

### ISSUE THREAD

**Issue by lljakll** [tuomount/Open-Realms-of-Stars#171]
Attempting to play on a 2K or 4K screen is difficult.  The graphics and text are almost too small to read/see. 
 Needs resolution options.  Maybe incorporated into a full screen option.

**Comment by tuomount** [comment]
Yes, I am aware of this problem. Problem is that I do not have 2K or 4K screen so that I could. What I have read that Java 9 improves scaling issues. As far as I know scaling issue is worst with Java8 and Windows operating systems. For some reason Java8 disabled HiDPI support from Windows.

**Comment by tuomount** [comment]
By 2K you meant Full HD, right? I do have Full HD and in theory some part of the screen could be then bigger, but simple doubling the current resolution would go above Full HD.

**Comment by tuomount** [comment]
I tried to make simple JFrame bigger but that will create some issues. Drawing the maps does not get bigger since those are only designed to work with single resolution.  There are quite a lot pixel art so getting things bigger is not trivial. Some of the component support scaling out of the box(Since they are based on Swing components). So there could be another resolution or even free scaling but that would require quite a lot of work on some components and still it might not help graphics/text are too small. But this would be easier.

Drawing all the map in double size is major amount of work since all the graphics would required to have two different resolutions or do the scaling simply double which could lead pixelated graphics.

Full screen seems to be possible for Java Swing but how it works seems to have some OS dependencies. https://stackoverflow.com/questions/11570356/jframe-in-full-screen-java#11570414

lljakll could please describe which text and graphics are too small to see and if you have 4K screen please try out Java9 or newer.

**Comment by tuomount** [comment]
Multiple resolution support has been done. There still migh be some views which require tweaking, but these can be fixed while verifying the issue.

**Comment by tuomount** [comment]
No fixes for a while and I haven't noticed anything not working for a week at least. Closing.
