### ISSUE TITLE
New base weapon: Chain gun

### ISSUE THREAD

**Issue by tuomount** [tuomount/Open-Realms-of-Stars#496]
While playing the game, I noticed that there could machine/chain/multi cannon/gun weapon. Idea would be that it would use regular bullets and would not require energy for shooting. How ever range would be always only 1, and base hit chance around 60%. It would pass 50% of shields and armor would function as normal. So in that sense weapon would be between railgun and missiles. In practice this would replace some base weapon for certain races. This would be nice weapon for Sporks and Smaugirians at least.

**Comment by ilhn** [comment]
Hi @tuomount  I want to work on this issue. Could you assign this issue to me ?

**Comment by tuomount** [comment]
Sure thing.

**Comment by ilhn** [comment]
Hi again, i have an error after typing 'mvn install' , i will copy the error text here : 

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project Open-Realm-of-Stars: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ? -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project Open-Realm-of-Stars: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ?

I am using Visual Studio Code and maven version 3.6.3. I downloaded the zip file of the code and extract in the folder which is named 'ProjectOs'. I have searched via Google and I have tried editing version of the surefireplugin version code in pom.xl file but that does not make any sense. Could you help me on this issue ?  Thanks for your help.

**Comment by tuomount** [comment]
I haven't seen this before. But I encountered some other project had similar issue. One problem was that Alpine Linux OpenJDK was corrupted: https://issues.apache.org/jira/browse/SUREFIRE-1478 
So could you tell me what OpenJDK version you are using?
Second case where Surefire plugin itself had bug: https://github.com/cbeust/testng/issues/1693
For this I upgraded Surefire plugin to 2.22.2 version. You can try this out getting pull from the repository.

I am using Following OpenJDK version:
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)

Maven is 3.6.3.

**Comment by ilhn** [comment]
It is still going with same error. I am gonna provide an attachment as a text file which contains the full terminal output.
My OpenJDK version is : 
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.2+12)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.2+12, mixed mode, sharing)
Could it be stem from the difference of version of OpenJDK?
Thanks again
[terminaloutput.txt](https://github.com/tuomount/Open-Realms-of-Stars/files/7688851/terminaloutput.txt)
.

**Comment by tuomount** [comment]
Looks like Jacoco is failing. Could you try updating it to 0.8.7 version which is latest available in Maven repository? I can do this later today, but not right now.

**Comment by ilhn** [comment]
It works and finally i got the .jar file in target directory. Thanks a lot.

**Comment by tuomount** [comment]
Now I am interested how did you fix this? This might be worth of pull request.

**Comment by ilhn** [comment]
I just edit the pom.xml file. In line 105 in pom.xml file, i have changed the version of jacoco to 0.8.7 as you said. 
Do you mind if we talk on another channel like Discord ? I am a beginner at open source projects and this project looks like a much more complex project than I thought.

**Comment by ilhn** [comment]
Okay i will send a request for that.

**Comment by tuomount** [comment]
I made Discord server for ORoS: https://discord.gg/bB5xQuts

**Comment by ilhn** [comment]
Ive sent another pull request. Ive tested all these files step by step with mvn install command.

**Comment by ilhn** [comment]
Thanks for the review of my last pull request. As I mentioned before i adjust hit chance as 50 for the test that you have written before in ShipTest.java class and also ShipTest2.java class. I could rewrite as 60 but i think we have to rewrite this test lines to build succesfully. 
I can also change the Callisto as a non-rare technology but there are some points that I dont understand clearly. 
The last thing i want to mention that tomorrow is the due date for my school project. Could you accept my request just for now ? Because my lecturer wants to see something concrete and visible. He wants to see what I have done so far and to do this I need to your approval firstly.
I do not want to be misunderstood, your approval is my first priority and I will give all my best to do it. I just mean that I have a limited time and we could go forward later.
I think we could discuss on discord again if u do not mind. I will wait for you there.

**Comment by ilhn** [comment]
I have 1 last will from you mister. I forgot to attach my lecturer as assignee to the my last pull request. If you do not mind could you add him ass an assignee to the project. I do not know it is available option but I thought that you could add him because you have the full permission as an owner of the repo. Thanks again. His nickname is @cagdasgerede on here.

**Comment by tuomount** [comment]
Github does not allow adding people unless they have said something in the issue thread. For example this issue I can only add either you or me.
