### ISSUE TITLE
how to start a game???

### ISSUE THREAD

**Issue by klade-png** [tuomount/Open-Realms-of-Stars#544]
I downloaded the game and when I went to start and finished checking all options I coudn't find a button to start game or press enter to start the game. please help..

**Comment by klade-png** [comment]
thanks and also the seems very intimidating and I'm pretty sure its fun is there like a video tutorial or how to play or something?
thanks and have a wonderful day or night!
regards, 
Klade

**Comment by tuomount** [comment]
I assume that setting scaling to 100% fixed the issue. I also tried reading how to fix other suggestions were to update Java JRE to version 9 or newer. Newest LTS 17 other common version is LTS 11. Currently there is no video tutorial, at least I haven't made myself, however there is textual tutorial which tries to explain things. Since game is not done yet and new features are made tutorial is not fully finished, but basic game play should be explained.

**Comment by tuomount** [comment]
There is now Let's Play video series in [Youtube](https://www.youtube.com/watch?v=sFfhuevjAo4&list=PLi-86pwymV0Ij6EBo1-bWdweOVKsbkAa1). First part covers pretty much all the basics how to play the game. Closing this issue now.
