### ISSUE TITLE
Governors cannot be told to stop managing the planet

### ISSUE THREAD

**Issue by BottledByte** [tuomount/Open-Realms-of-Stars#639]
As a player, I want to reap the bonuses from having a planet managed by a governor. However, if I assign them I cannot unassign them, nor I cannot tell them to leave the planet construction queue management to me. I may have my own plans with the planet and collide with governor's actions.

There does not necessarily need to be an option to unassign a governor, although it would be nice to have.
However, *there has to be an option to disable governor's planetary "auto-management"*, as the latter can become very annoying. An option "Disabled" or similar should be available as a Governor Guide in the planetary view, to disable the auto-management.

**Comment by tuomount** [comment]
That is designed that governors or commander cannot be reassigned unless they have been in their current job 20 star years. Then maybe selected for ruler before that. This is because some of the perks rulers can gain are bad, they might for example be come corrupted.
How ever when governor makes building project selection player can go and select something different like there would not be any governor. Governor just makes the automatic selection, but there is message that something like "building project has been built in planet XYZ. Governor selected building project foobar next project." Clicking focus should go to planet and it can be changed if wanted or needed.

Of course there could be option to disable governor's auto-management. What do you think is above functionality enough or should there be disabling auto-management?

**Comment by tuomount** [comment]
Yes, true it is not mentioned in tutorial, it should be. Only clue for this feature is when viewing leaders and you can see how many star years he/she has been as governor/commander it says assignable after 20 star years.

Let's take this to 0.25.0Beta, it shouldn't be big task. Plus with this same issue tutorial text should be improved.
