### ISSUE TITLE
Refactor Fleet movement code for AI

### ISSUE THREAD

**Issue by BottledByte** [tuomount/Open-Realms-of-Stars#647]
Majority of the game's AI code is inside `MissionHandling.java`. Inside, there are two *overloaded methods* for moving fleets, `makeFleetMove()`. One would think that they do the same thing, only one being a shorthand for accepting coordinates as a compact type, while the other decomposed. **Upon closer inspection, the methods have DIFFERENT logic in their body!** And are called in different places in the codebase. Yet, they share the same Javadoc documentation text...

To make things even worse, both methods eventually call a method of very similar name, `fleetMakeMove()`, from `Game` object. And at first glance, it seems that this method duplicates small parts of logic inside `MissionHandling.fleetMakeMove()` methods.

In this case, it is not obvious, what the code should and shouldn't do, nor it is documented enough. And as both methods in `MissionHandling` have similar parts of code, this calls for refactoring/deduplication. However, I cannot safely refactor this, without understanding the code better.

@tuomount Can you please explain what is going on in this part of code and what it should do?

**Comment by tuomount** [comment]
```
MissionHandling.fleetMakeMove(final Game game, final int nx, final int ny,
      final PlayerInfo info, final Fleet fleet)
``` is used only when fleet are moving with FTL routes.
```
MissionHandling.fleetMakeMove(final Game game, final PathPoint point,
      final PlayerInfo info, final Fleet fleet)
``` is used when fleet is moving with standard moves where PathPoints were calculated with A* search. Both of these method then call `game.fleetMakeMove()` which does the actual fleet moving. Reason why this is in game is that there can be game state change during fleet move for example attack or diplomatic trade and only place where to make game state changes is Game class.

They have different logic since they check a bit different things while moving in FTL and while moving with regular moves. For example FTL movement should not start combat, only when moved with same sector with regular move. Javadocs are horrible, since they are identical. I also think that this part in pathpoint fleetMakeMove is dead code.
```
 else {
          Message msg = new Message(MessageType.FLEET,
              "Fleet encounter another fleet while moving in FTL!",
              Icons.getIconByName(Icons.ICON_HULL_TECH));
          msg.setCoordinate(fleet.getCoordinate());
          msg.setMatchByString(fleet.getName());
          info.getMsgList().addNewMessage(msg);
        }
```
