### ISSUE TITLE
Moving game data definitons to data files

### ISSUE THREAD

**Issue by BottledByte** [tuomount/Open-Realms-of-Stars#666]
Continuation of discussion from #665 about de-hardcoding game data into data files.

---
TLDR:
1. I want to move as much as possible game data definitions out from Java code.
2. **It must be some common format**, not a custom one.
3. I don't want to reinvent the wheel, writing custom parsers/serializers.
4. I don't want to pull in large and/or unnecessary dependencies.
5. As a programmer, I want simple API to work with stored data.
---

**Comment by Zireael07** [comment]
As the most recent comment says, JSON is widely used for that purpose. (Cata:DDA is indeed a great example)

**Comment by tuomount** [comment]
I think there should be an issue for each data definition and first needs to define how to store data in JSON. For example in speech there could root level Speech, under it each space race and under each spacerace the actual lines. And yes I like that variation.

So obvious ones are factories: ShipHullFactory, ShipComponentFactory, ArtifactFactory, TechFactory, BuildingFactory
Then not factories, these might be a bit more trickier to implement: SpaceRace, Government, PlanetTypes, WorldType, PlanetTypes, LeaderPerks

I would not try convert all of these at same time, since it would cause massive amount of testing. Plus I am also working with new ascension victory where I need to touch a bit there and here in code. I have been rebasing quite often so I am still good.

**Comment by tuomount** [comment]
I am actually thinking that if 0.25.0 release should be done without Ascension victory. Current version has highly improved map drawing which increases performance on lower pcs plus other improvements. Then there would be just testing that all the features work.

After this internal redesign could be started more safely. Also that new JSON-in-Java could be bring in. These redesign could be started on separate branch and later merge that to master.

Yes, I agree your plan sounds really good.

**Comment by tuomount** [comment]
Redesign/refactor is easier on `master` but if you have lot's merge requests waiting, these could be place on separate branch. But I agree it is easier keep master where features/redesign/refactors are merged.

I check all the current issues which are open there are still two perks missing, but these could be also moved to 0.26.0 and then there is the feature you suggested that governor should not choose for next building project. After this there is testing left. I would like to play at least one full game, and hopefully it can played without no issues. If that's the case I think next release can be done.

**Comment by tuomount** [comment]
Lot's of data moved into JSON. Closing.
