### ISSUE TITLE
Proper design for Space Pirates and "pseudo realms"

### ISSUE THREAD

**Issue by BottledByte** [tuomount/Open-Realms-of-Stars#713]
There are two `SpaceRace`s which are not real races, `SPACE_PIRATE` and `SPACE_MONSTERS`.
Those two pseudo races make `SpaceRace` more difficult to define and are negatively impacting generic code for handling races when they will be dehardcoded.

Both "races" are used primarily for "board players", which are not "real" realms.
Such "pseudo" realms need a proper system and not rely on the `SpaceRace` enum for their definition.

**Comment by tuomount** [comment]
This decision was done, since I could use similar handling for those as any other realm including AI, how to get graphics etc. I was thinking when SpaceRace is proper class and not enum, these could created during star map creation based for example Human and just change the graphics, dialog and such. Then these pseudo races would not interference with other space races.

**Comment by tuomount** [comment]
Closing.
