### ISSUE TITLE
Armed freighters mechanic design

### ISSUE THREAD

**Issue by BottledByte** [tuomount/Open-Realms-of-Stars#726]
"Smaugirians" SpaceRace has special "smuggling" mechanic, where freighter Ships can be armed - without being reported as armed.
 
It seems to me that "smuggling" game mechanic is not based on race's physique and thus *it cannot be a `RaceTrait`*.
It feels more like it is a `Government` thing and should be relocated there.

Maybe the Government is fine with such "low" tactics, arming civilian ships  (i.e. Syndicate, Regime, Pirates, etc.)?
Or the Government allows (rich) civilians/individuals to have access to ship-grade weaponry (i.e. Guild, Enterprise, etc.)?

In any case, such change would technically render whole "Smaugirians" race obsolete in terms of unique gameplay, as having secretly armed freighters is it's only "unusual property". And thus, the SpaceRace could be deleted - similar situation like with Alonians without a special start.

Also, the mechanic could use a better name :smile:

**Comment by tuomount** [comment]
Smaugirians got inspiration from Firefly(TV series) and Star War's Han Solo. Han Solo in many RPGs has class called Scoundrel, but that is also adjective. I would think that scoundrel could describe armed freighters mechanic a bit similarly as stealthy for built-in cloaking device. What do you think?

**Comment by tuomount** [comment]
That armed freighters sounds actually good description for mechanic. Currently Smaugirians also have ability to add privateer modules, but I would drop that. But adding privateer modules any ships could fit on other hand Pirates/Syndicate/Regime government.

**Comment by tuomount** [comment]
> I don't see an argument that would justify "Scoundrel" `RaceTrait`. After all, you describe that the mechanic is inspired by humans, so that means the trait **would have to be shared with Humans, not only Smaugirians**. Additionally, the mechanic alters ship design greatly.
> 
True, all my examples where from Humans.

> **Ship design should be tied to `SpaceRace` as loosely as possible.** And it should be considered a Realm-thing (in code -> `PlayerInfo`).
> 
At some point we could have biological race which would grow their own ships a bit like space monster at the moment in game. But this would be quite big change, since most of the technology needs to be changed. But this could be quite interesting.

> So no, I don't see "Scoundrel" `RaceTrait` as good idea long-term. _It **could be a hack** until proper design is implemented, so it does not block `SpaceRace` dehardcoding._
> 

Maybe go with hack. Make RaceTrait called Armed freighters or something obvious that it needs to be changed. I would like to keep space races like this still in game.

> > But adding privateer modules any ships could fit on other hand Pirates/Syndicate/Regime government.
> 
> Agreed. But I don't see how that is different from "secret" weapons in freighters. 🙂

After sleeping over night, armed freighters is government thing, or maybe even ruler perk thing. So that under certain ruler, "rules" could be bend. :smile:  At some point also government should have government traits so those could be also easy to edit/modify.

But for now I would go with some hack, so that Smaugirians would still be in game.

**Comment by tuomount** [comment]
I found actually pretty easy solution for this. That armed freighter trait check was done only few places and trick was just change the ship design limitation based on government. Now ships may have weapons in freighter and if so they are technically always smuggler ships. This is allowed only if government has armed freighters flag.

**Comment by tuomount** [comment]
Works. Closing.
